/*

 CLOUDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\CloudTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 23
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __cloudmap_h_INCLUDE
#define __cloudmap_h_INCLUDE

#define cloudmapWidth 20
#define cloudmapHeight 1
#define cloudmapBank 0

extern const unsigned char cloudmap[];

#endif

/* End of CLOUDMAP.H */
