/*

 CLOUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\CloudTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 42
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cloudmapWidth 20
#define cloudmapHeight 1
#define cloudmapBank 0

const unsigned char cloudmap[] =
{
  0x2B,0x2C,0x30,0x2D,0x30,0x2B,0x2C,0x30,0x2D,0x2F,
  0x30,0x2D,0x2C,0x2D,0x2C,0x2E,0x2F,0x2C,0x2B,0x2B
};

/* End of CLOUDMAP.C */
