/*

 CLOUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\CloudTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 23
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cloudmapWidth 20
#define cloudmapHeight 1
#define cloudmapBank 0

const unsigned char cloudmap[] =
{
  0x18,0x19,0x1D,0x1A,0x1D,0x18,0x19,0x1D,0x1A,0x1C,
  0x1D,0x1A,0x19,0x1A,0x19,0x1B,0x1C,0x19,0x18,0x18
};

/* End of CLOUDMAP.C */
