/*

 DESERTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 9
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DesertZoneBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 60
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __desertmap_h_INCLUDE
#define __desertmap_h_INCLUDE

#define desertmapWidth 32
#define desertmapHeight 9
#define desertmapBank 0

extern const unsigned char desertmap[];

#endif

/* End of DESERTMAP.H */
