/*

 GOODROADMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __goodroadmap_h_INCLUDE
#define __goodroadmap_h_INCLUDE

#define goodroadmapWidth 3
#define goodroadmapHeight 7
#define goodroadmapBank 0

extern const unsigned char goodroadmap[];

#endif

/* End of GOODROADMAP.H */
