/*

 GOODROADMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 72
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define goodroadmapWidth 3
#define goodroadmapHeight 7
#define goodroadmapBank 0

const unsigned char goodroadmap[] =
{
  0x48,0x48,0x48,0x00,0x00,0x00,0x4C,0x4D,0x00,0x4A,
  0x4B,0x00,0x4E,0x4F,0x00,0x00,0x00,0x00,0x49,0x49,
  0x49
};

/* End of GOODROADMAP.C */
