/*

 GOODROADMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define goodroadmapWidth 3
#define goodroadmapHeight 7
#define goodroadmapBank 0

const unsigned char goodroadmap[] =
{
  0x01,0x01,0x01,0x00,0x00,0x00,0x03,0x04,0x00,0x00,
  0x00,0x00,0x03,0x04,0x00,0x00,0x00,0x00,0x02,0x02,
  0x02
};

/* End of GOODROADMAP.C */
