/*

 HOLEENDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holeendmapWidth 3
#define holeendmapHeight 7
#define holeendmapBank 0

const unsigned char holeendmap[] =
{
  0x09,0x09,0x01,0x1A,0x14,0x00,0x13,0x15,0x00,0x16,
  0x17,0x00,0x18,0x08,0x00,0x19,0x00,0x00,0x02,0x02,
  0x02
};

/* End of HOLEENDMAP.C */
