/*

 HOLEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 72
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holemapWidth 3
#define holemapHeight 7
#define holemapBank 0

const unsigned char holemap[] =
{
  0x50,0x50,0x50,0x61,0x61,0x61,0x5A,0x5A,0x5A,0x5A,
  0x5A,0x5A,0x5A,0x5A,0x5A,0x5A,0x5A,0x5A,0x63,0x63,
  0x63
};

/* End of HOLEMAP.C */
