/*

 HUDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\HUDTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 29
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __hudmap_h_INCLUDE
#define __hudmap_h_INCLUDE

#define hudmapWidth 18
#define hudmapHeight 1
#define hudmapBank 0

extern const unsigned char hudmap[];

#endif

/* End of HUDMAP.H */
