/*

 HUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\HUDTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 29
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 18
#define hudmapHeight 1
#define hudmapBank 0

const unsigned char hudmap[] =
{
  0x29,0x2A,0x2E,0x31,0x31,0x31,0x31,0x1D,0x1D,0x1D,
  0x1D,0x1D,0x1D,0x1D,0x1D,0x2F,0x2E,0x21
};

/* End of HUDMAP.C */
