/*

 HUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\HUDTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 25
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 18
#define hudmapHeight 1
#define hudmapBank 0

const unsigned char hudmap[] =
{
  0x24,0x25,0x26,0x29,0x29,0x29,0x29,0x19,0x19,0x19,
  0x19,0x19,0x19,0x19,0x19,0x27,0x26,0x1D
};

/* End of HUDMAP.C */
