/*

 MISCTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char misctiles[] =
{
  0x03,0x03,0x07,0x05,0x0E,0x0A,0x1E,0x12,
  0x3E,0x22,0x7C,0x44,0xFC,0x84,0x00,0x00
};

/* End of MISCTILES.C */
