/*

 SCORPBOSSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 6
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\ScorpbotBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 80
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __scorpbossmap_h_INCLUDE
#define __scorpbossmap_h_INCLUDE

#define scorpbossmapWidth 9
#define scorpbossmapHeight 6
#define scorpbossmapBank 0

extern const unsigned char scorpbossmap[];

#endif

/* End of SCORPBOSSMAP.H */
