/*

 VOLCANICLVLMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 9
   Tile set      : C:\Users\Konstantin\Desktop\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\VolcanoZoneBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 31
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __volcaniclvlmap_h_INCLUDE
#define __volcaniclvlmap_h_INCLUDE

#define volcaniclvlmapWidth 20
#define volcaniclvlmapHeight 9
#define volcaniclvlmapBank 0

extern const unsigned char volcaniclvlmap[];

#endif

/* End of VOLCANICLVLMAP.H */
