/*

 AIRBASEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 11
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\AirbaseMapTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __airbasemap_h_INCLUDE
#define __airbasemap_h_INCLUDE

#define airbasemapWidth 20
#define airbasemapHeight 11
#define airbasemapBank 0

extern const unsigned char airbasemap[];

#endif

/* End of AIRBASEMAP.H */
