/*

 CITYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 9
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\CityZoneBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 61
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __citymap_h_INCLUDE
#define __citymap_h_INCLUDE

#define citymapWidth 32
#define citymapHeight 9
#define citymapBank 0

extern const unsigned char citymap[];

#endif

/* End of CITYMAP.H */
