/*

 CLOUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 1
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\CloudTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 52
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cloudmapWidth 32
#define cloudmapHeight 1
#define cloudmapBank 0

const unsigned char cloudmap[] =
{
  0x34,0x35,0x36,0x3C,0x3D,0x3E,0x3F,0x40,0x34,0x38,
  0x39,0x35,0x36,0x3C,0x3D,0x3E,0x3F,0x40,0x37,0x38,
  0x39,0x39,0x3A,0x3B,0x3C,0x3D,0x3E,0x3F,0x40,0x34,
  0x35,0x36
};

/* End of CLOUDMAP.C */
