/*

 DEFSYSBOSSCEILGUNMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 2
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DefenceSystemBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __defsysbossceilgunmap_h_INCLUDE
#define __defsysbossceilgunmap_h_INCLUDE

#define defsysbossceilgunmapWidth 3
#define defsysbossceilgunmapHeight 2
#define defsysbossceilgunmapBank 0

extern const unsigned char defsysbossceilgunmap[];

#endif

/* End of DEFSYSBOSSCEILGUNMAP.H */
