/*

 DEFSYSBOSSDOORHOLEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DefenceSystemBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define defsysbossdoorholemapWidth 4
#define defsysbossdoorholemapHeight 5
#define defsysbossdoorholemapBank 0

const unsigned char defsysbossdoorholemap[] =
{
  0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAE,0xAF,0x26,0xB0,
  0xAE,0xB1,0x24,0xB2,0xB3,0xB4,0x28,0xFF,0xB5,0xA1
};

/* End of DEFSYSBOSSDOORHOLEMAP.C */
