/*

 DEFSYSBOSSDOORHOLEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DefenceSystemBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define defsysbossdoorholemapWidth 4
#define defsysbossdoorholemapHeight 5
#define defsysbossdoorholemapBank 0

const unsigned char defsysbossdoorholemap[] =
{
  0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xCF,0xD0,0x47,0xD1,
  0xCF,0xD2,0x45,0xD3,0xD4,0xD5,0x49,0x00,0xD6,0xC2
};

/* End of DEFSYSBOSSDOORHOLEMAP.C */
