/*

 DEFSYSBOSSCEILGUNMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 2
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DefenceSystemBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define defsysbossceilgunmapWidth 3
#define defsysbossceilgunmapHeight 2
#define defsysbossceilgunmapBank 0

const unsigned char defsysbossceilgunmap[] =
{
  0xA3,0xA4,0xA5,0xA6,0xA7,0xA8
};

/* End of DEFSYSBOSSCEILGUNMAP.C */
