/*

 DEFSYSBOSSDOORHOLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DefenceSystemBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __defsysbossdoorholemap_h_INCLUDE
#define __defsysbossdoorholemap_h_INCLUDE

#define defsysbossdoorholemapWidth 4
#define defsysbossdoorholemapHeight 5
#define defsysbossdoorholemapBank 0

extern const unsigned char defsysbossdoorholemap[];

#endif

/* End of DEFSYSBOSSDOORHOLEMAP.H */
