/*

 DEFSYSBOSSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 16
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\DefenceSystemBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __defsysbossmap_h_INCLUDE
#define __defsysbossmap_h_INCLUDE

#define defsysbossmapWidth 4
#define defsysbossmapHeight 16
#define defsysbossmapBank 0

extern const unsigned char defsysbossmap[];

#endif

/* End of DEFSYSBOSSMAP.H */
