/*

 ENCOREBOSSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 17
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\EnergyCoreZoneBkgTiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 104
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __encorebossmap_h_INCLUDE
#define __encorebossmap_h_INCLUDE

#define encorebossmapWidth 6
#define encorebossmapHeight 17
#define encorebossmapBank 0

extern const unsigned char encorebossmap[];

#endif

/* End of ENCOREBOSSMAP.H */
