/*

 ENCOREBOSSNOBARRIERMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\EnergyCoreZoneBkgTiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 104
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __encorebossnobarriermap_h_INCLUDE
#define __encorebossnobarriermap_h_INCLUDE

#define encorebossnobarriermapWidth 6
#define encorebossnobarriermapHeight 7
#define encorebossnobarriermapBank 0

extern const unsigned char encorebossnobarriermap[];

#endif

/* End of ENCOREBOSSNOBARRIERMAP.H */
