/*

 ENCOREPREMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 10
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\EnergyCoreZoneBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 41
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __encorepremap_h_INCLUDE
#define __encorepremap_h_INCLUDE

#define encorepremapWidth 8
#define encorepremapHeight 10
#define encorepremapBank 0

extern const unsigned char encorepremap[];

#endif

/* End of ENCOREPREMAP.H */
