/*

 ENCOREBOSSBKGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 14 x 17
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\EnergyCoreZoneBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 41
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __encorebossbkgmap_h_INCLUDE
#define __encorebossbkgmap_h_INCLUDE

#define encorebossbkgmapWidth 14
#define encorebossbkgmapHeight 17
#define encorebossbkgmapBank 0

extern const unsigned char encorebossbkgmap[];

#endif

/* End of ENCOREBOSSBKGMAP.H */
