/*

 ENDINGCUTSCMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 8
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\EndingCutsceneTilesInvertedBlackAndWhite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __endingcutscmap_h_INCLUDE
#define __endingcutscmap_h_INCLUDE

#define endingcutscmapWidth 18
#define endingcutscmapHeight 8
#define endingcutscmapBank 0

extern const unsigned char endingcutscmap[];

#endif

/* End of ENDINGCUTSCMAP.H */
