/*

 GOODROADMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define goodroadmapWidth 3
#define goodroadmapHeight 7
#define goodroadmapBank 0

const unsigned char goodroadmap[] =
{
  0x21,0x21,0x21,0x00,0x00,0x00,0x25,0x26,0x00,0x23,
  0x24,0x00,0x27,0x28,0x00,0x00,0x00,0x00,0x22,0x22,
  0x22
};

/* End of GOODROADMAP.C */
