/*

 GOODROADMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define goodroadmapWidth 3
#define goodroadmapHeight 7
#define goodroadmapBank 0

const unsigned char goodroadmap[] =
{
  0x42,0x42,0x42,0x00,0x00,0x00,0x46,0x47,0x00,0x44,
  0x45,0x00,0x48,0x49,0x00,0x00,0x00,0x00,0x43,0x43,
  0x43
};

/* End of GOODROADMAP.C */
