/*

 HOLEENDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __holeendmap_h_INCLUDE
#define __holeendmap_h_INCLUDE

#define holeendmapWidth 3
#define holeendmapHeight 7
#define holeendmapBank 0

extern const unsigned char holeendmap[];

#endif

/* End of HOLEENDMAP.H */
