/*

 HOLESTARTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __holestartmap_h_INCLUDE
#define __holestartmap_h_INCLUDE

#define holestartmapWidth 4
#define holestartmapHeight 7
#define holestartmapBank 0

extern const unsigned char holestartmap[];

#endif

/* End of HOLESTARTMAP.H */
