/*

 HOLESTARTMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 72
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holestartmapWidth 4
#define holestartmapHeight 7
#define holestartmapBank 0

const unsigned char holestartmap[] =
{
  0x48,0x48,0x48,0x50,0x00,0x00,0x51,0x52,0x4C,0x4D,
  0x53,0x57,0x4A,0x54,0x55,0x5A,0x4E,0x56,0x57,0x5A,
  0x00,0x58,0x5A,0x5A,0x49,0x59,0x63,0x63
};

/* End of HOLESTARTMAP.C */
