/*

 HOLEENDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holeendmapWidth 3
#define holeendmapHeight 7
#define holeendmapBank 0

const unsigned char holeendmap[] =
{
  0x29,0x29,0x21,0x3A,0x34,0x00,0x33,0x35,0x00,0x36,
  0x37,0x00,0x38,0x28,0x00,0x39,0x00,0x00,0x22,0x22,
  0x22
};

/* End of HOLEENDMAP.C */
