/*

 HOLESTARTMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holestartmapWidth 4
#define holestartmapHeight 7
#define holestartmapBank 0

const unsigned char holestartmap[] =
{
  0x42,0x42,0x42,0x4A,0x00,0x00,0x4B,0x4C,0x46,0x47,
  0x4D,0x51,0x44,0x4E,0x4F,0x54,0x48,0x50,0x51,0x54,
  0x00,0x52,0x54,0x54,0x43,0x53,0x5D,0x5D
};

/* End of HOLESTARTMAP.C */
