/*

 HOLEENDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 72
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holeendmapWidth 3
#define holeendmapHeight 7
#define holeendmapBank 0

const unsigned char holeendmap[] =
{
  0x50,0x50,0x48,0x61,0x5B,0x00,0x5A,0x5C,0x00,0x5D,
  0x5E,0x00,0x5F,0x4F,0x00,0x60,0x00,0x00,0x49,0x49,
  0x49
};

/* End of HOLEENDMAP.C */
