/*

 HOLEENDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 7
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\RoadTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holeendmapWidth 3
#define holeendmapHeight 7
#define holeendmapBank 0

const unsigned char holeendmap[] =
{
  0x4A,0x4A,0x42,0x5B,0x55,0x00,0x54,0x56,0x00,0x57,
  0x58,0x00,0x59,0x49,0x00,0x5A,0x00,0x00,0x43,0x43,
  0x43
};

/* End of HOLEENDMAP.C */
