/*

 HUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\HUDTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 18
#define hudmapHeight 1
#define hudmapBank 0

const unsigned char hudmap[] =
{
  0x06,0x07,0x0B,0x0E,0x0E,0x0E,0x0E,0x00,0x00,0x0C,
  0x11,0x0D,0x00,0x00,0x00,0x10,0x0B,0x04
};

/* End of HUDMAP.C */
