/*

 HUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\HUDTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 18
#define hudmapHeight 1
#define hudmapBank 0

const unsigned char hudmap[] =
{
  0x18,0x21,0x2E,0x03,0x03,0x03,0x03,0x00,0x00,0x01,
  0x06,0x02,0x00,0x00,0x00,0x05,0x2E,0x00
};

/* End of HUDMAP.C */
