/*

 INTROSCREEN2MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 8
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\IntroScreen2Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __introscreen2map_h_INCLUDE
#define __introscreen2map_h_INCLUDE

#define introscreen2mapWidth 12
#define introscreen2mapHeight 8
#define introscreen2mapBank 0

extern const unsigned char introscreen2map[];

#endif

/* End of INTROSCREEN2MAP.H */
