/*

 INTROSCREEN3MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 8
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\IntroScreen3Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __introscreen3map_h_INCLUDE
#define __introscreen3map_h_INCLUDE

#define introscreen3mapWidth 8
#define introscreen3mapHeight 8
#define introscreen3mapBank 0

extern const unsigned char introscreen3map[];

#endif

/* End of INTROSCREEN3MAP.H */
