/*

 INTROSCREEN1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 14 x 8
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\IntroScreen1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __introscreen1map_h_INCLUDE
#define __introscreen1map_h_INCLUDE

#define introscreen1mapWidth 14
#define introscreen1mapHeight 8
#define introscreen1mapBank 0

extern const unsigned char introscreen1map[];

#endif

/* End of INTROSCREEN1MAP.H */
