/*

 JUGGERNAUTBOSSMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 5
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\JuggernautBossTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __juggernautbossmap2_h_INCLUDE
#define __juggernautbossmap2_h_INCLUDE

#define juggernautbossmap2Width 9
#define juggernautbossmap2Height 5
#define juggernautbossmap2Bank 0

extern const unsigned char juggernautbossmap2[];

#endif

/* End of JUGGERNAUTBOSSMAP2.H */
