/*

 MOUNTAINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 9
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\MountainZoneBkgTiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 61
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mountainmap_h_INCLUDE
#define __mountainmap_h_INCLUDE

#define mountainmapWidth 32
#define mountainmapHeight 9
#define mountainmapBank 0

extern const unsigned char mountainmap[];

#endif

/* End of MOUNTAINMAP.H */
