/*

 OVERWORLDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 11
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\OverworldMapTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __overworldmap_h_INCLUDE
#define __overworldmap_h_INCLUDE

#define overworldmapWidth 20
#define overworldmapHeight 11
#define overworldmapBank 0

extern const unsigned char overworldmap[];

#endif

/* End of OVERWORLDMAP.H */
