/*

 PASSWSCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\FontPlusPassScrTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 1
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __passwscreenmap_h_INCLUDE
#define __passwscreenmap_h_INCLUDE

#define passwscreenmapWidth 20
#define passwscreenmapHeight 18
#define passwscreenmapBank 0

extern const unsigned char passwscreenmap[];

#endif

/* End of PASSWSCREENMAP.H */
