/*

 TITLELOGOMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 6
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\TitleLogoTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 33
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __titlelogomap_h_INCLUDE
#define __titlelogomap_h_INCLUDE

#define titlelogomapWidth 16
#define titlelogomapHeight 6
#define titlelogomapBank 0

extern const unsigned char titlelogomap[];

#endif

/* End of TITLELOGOMAP.H */
