/*

 TUNNELMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 10
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\HoverAssault\TunnelZoneBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 61
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tunnelmap_h_INCLUDE
#define __tunnelmap_h_INCLUDE

#define tunnelmapWidth 32
#define tunnelmapHeight 10
#define tunnelmapBank 0

extern const unsigned char tunnelmap[];

#endif

/* End of TUNNELMAP.H */
