/*

 AIRBASEMAPTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 1 to 116

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __airbasemaptiles_h_INCLUDE
#define __airbasemaptiles_h_INCLUDE

/* Bank of tiles. */
#define airbasemaptilesBank 0
/* Start of tile array. */
extern const unsigned char airbasemaptiles[];

#endif

/* End of AIRBASEMAPTILES.H */
