/*

 FORTSFIRETILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char fortsfiretiles[] =
{
  0x00,0x00,0x00,0x00,0x08,0x00,0x20,0x00,
  0x0A,0x00,0x50,0x04,0x01,0x28,0x20,0x4A,
  0x20,0x00,0x82,0x00,0x28,0x00,0x51,0x04,
  0x08,0x82,0x00,0x54,0x01,0x28,0x20,0x4A
};

/* End of FORTSFIRETILES.C */
