/*

 MISCTILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char misctiles[] =
{
  0x60,0x60,0x38,0x38,0x16,0x1E,0x1F,0x11,
  0x26,0x3E,0x78,0x78,0xC0,0xC0,0x00,0x00
};

/* End of MISCTILES.C */
